spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  camunda:
    bpm:
      database:
        schema-update: true
      admin-user:
        id: admin
        password: admin
